theme: jekyll-theme-slate
title: Giorgos Papageorgiou
description: Irregualr project updates relating to things in applied maths, geophysics, software
avatar: https://avatars.githubusercontent.com/gpap-gpap
markdown: kramdown
