theme: jekyll-theme-slate
title: Giorgos Papageorgiou
description: Irregualr project updates relating to things in applied maths, geophysics, software
avatar: https://avatars.githubusercontent.com/gpap-gpap
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
